name: Terraform Deploy

on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      USER1: ${{ secrets.USER1 }}
      PASSWORD1: ${{ secrets.PASSWORD1 }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TF_VAR_GCP_CREDENTIALS }}

      - name: Terraform Plan
        run:  terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TF_VAR_GCP_CREDENTIALS }}


      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TF_VAR_GCP_CREDENTIALS }}